spring.cache.type=redis

#spring.cache.cache-names=
spring.cache.redis.time-to-live=3600000
# If we specify a prefix, the prefix we specify will be used. If not, the cached name will be used as the prefix by default.
#spring.cache.redis.key-prefix=CACHE_
spring.cache.redis.use-key-prefix=true
# Whether to cachenullvalue. Prevent cache penetration
spring.cache.redis.cache-null-values=true

gulimall.thread.core-size=20
gulimall.thread.max-size=200
gulimall.thread.keep-alive-time=10